version: '3.8'

services:
  db:
    image: postgres
    container_name: announcement-app-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: announcement-db
    volumes:
      - db:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: announcement-app-redis-container
    ports:
      - "6379:6379"

volumes:
  db:

